# Generated by Django 3.2.5 on 2021-08-29 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('mobile', models.IntegerField(max_length=12)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='mm/dd/yy')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=80)),
                ('address', models.CharField(max_length=200, null=True)),
                ('graduation', models.CharField(blank=True, max_length=100, null=True)),
                ('post_graduation', models.CharField(blank=True, max_length=100, null=True)),
                ('experiance', models.IntegerField(verbose_name='months')),
                ('resume', models.FileField(null=True, upload_to='resume')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employer.job')),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25)),
                ('created', models.CharField(max_length=25)),
                ('status', models.CharField(choices=[('apply', 'apply'), ('cancelled', 'cancelled')], default='apply', max_length=80)),
                ('active_status', models.BooleanField(default=True)),
                ('jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employer.job')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseeker.profile')),
            ],
        ),
    ]
