# Generated by Django 3.2.5 on 2021-09-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0002_alter_job_last_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('part-time', 'part-time'), ('full-time', 'full-time'), ('internship', 'internship')], max_length=10),
        ),
    ]
